version: 0.2
env:
    variables:
        S3_BUCKET: "dev.demotest"
        BUILD_ENV: "prod"
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}
    post_build:
         commands:
            - aws s3 sync ./dist/musicpub s3://${S3_BUCKET} --acl 'public-read' --delete
            - echo Build completed   `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/musicpub'
    discard-paths: yes